// LOCALHOST
###
GET http://localhost:8080/house
###
GET http://localhost:8080/house/67448f9db48ff4702dd4b6d3
###
POST http://localhost:8080/house HTTP/1.1
Content-Type: application/json

{
    "location": "3rd floor",
    "information": "this house is greatish",
    "password": "password"
}
###
PUT http://localhost:8080/house/674693051b12a84d8a356310 HTTP/1.1
Content-Type: application/json

{
    "house": "Slytherin",
    "location": "Dungeons",
    "information": "Members of this house often have shadows cast over them. However, they are ambitous and seek greatness.",
    "password": "For the greater good."
}
###
DELETE http://localhost:8080/house/67553c4df4beefed29903372 HTTP/1.1
###
GET http://localhost:8080/class
###
GET http://localhost:8080/class/67450d39e8924de0546355fc
###
POST http://localhost:8080/class HTTP/1.1
Content-Type: application/json

{
    "className": "herbology",
    "recipes": "earmuffs"
}
###
PUT http://localhost:8080/class/67450d39e8924de0546355fc HTTP/1.1
Content-Type: application/json

{
    "className": "potions",
    "recipes": "boomslang skin"
}
###
DELETE http://localhost:8080/class/67452ce6f23e132d5a7fa438 HTTP/1.1
###
GET http://localhost:8080/floor
###
GET http://localhost:8080/floor/67452d3af23e132d5a7fa439
###
POST http://localhost:8080/floor HTTP/1.1
Content-Type: application/json

{
    "floorNum": "6th floor",
    "permission": "Prefects floor"
}
###
PUT http://localhost:8080/floor/67452d3af23e132d5a7fa439 HTTP/1.1
Content-Type: application/json

{
    "floorNum": "3rd floor",
    "permission": "Nope, Fluffy is here"
}
###
DELETE http://localhost:8080/floor/67452d3af23e132d5a7fa439 HTTP/1.1
###
GET http://localhost:8080/student
###
GET http://localhost:8080/student/67452d95f23e132d5a7fa43a
###
POST http://localhost:8080/student HTTP/1.1
Content-Type: application/json

{
    "firstName": "Hermione",
    "middleName": "Jane",
    "lastName": "Granger",
    "year": "1st",
    "house": "Gryffindor",
    "birthday": "07/25/2000",
    "userId": "008"
}
###
POST http://localhost:8080/student HTTP/1.1
Content-Type: application/json

{
    "firstName": "Captain",
    "middleName": "Stud",
    "lastName": "Awesome",
    "year": "1",
    "birthday": "07/25/2000",
    "userId": "0010"
}
###
PUT http://localhost:8080/student/67452d95f23e132d5a7fa43a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Hermione",
    "middleName": "J",
    "lastName": "Granger",
    "year": "1st",
    "house": "Gryffindor",
    "birthday": "07/25/2000",
    "userId": "008"
}
###
DELETE http://localhost:8080/student/67563c46d5875961677e1a21 HTTP/1.1


###
GET https://cse341-groupfinal-vz4q.onrender.com/student